# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shouhin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shouhin_cd', models.IntegerField(verbose_name='商品コード')),
                ('Shouhin_nm', models.CharField(max_length=256, verbose_name='商品名')),
                ('Kikaku', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('Siresaki_cd', models.IntegerField()),
                ('Siresaki_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('Irisu', models.CharField(max_length=100, null=True)),
                ('Siretanka', models.FloatField(default=True, max_length=20)),
            ],
            options={
                'verbose_name': '商品マスタ',
                'verbose_name_plural': '商品マスタClass',
            },
        ),
        migrations.CreateModel(
            name='T_oml2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('In_time', models.DateTimeField(verbose_name='登録年月日')),
                ('Hachu_no', models.CharField(max_length=6, verbose_name='発注書No')),
                ('Irai_day', models.DateTimeField(verbose_name='依頼日')),
                ('Busyo', models.CharField(blank=True, max_length=80, null=True, verbose_name='部署')),
                ('Irai_nm', models.CharField(max_length=80, null=True, verbose_name='依頼者')),
                ('Houhou', models.CharField(blank=True, max_length=80, null=True, verbose_name='方法')),
                ('Syuka_kokyaku', models.CharField(blank=True, max_length=200, null=True, verbose_name='出荷顧客')),
                ('Hachu_nm', models.CharField(max_length=80, verbose_name='発注者')),
                ('Bunrui', models.CharField(max_length=80, verbose_name='分類')),
                ('Iri_su', models.IntegerField(blank=True, null=True, verbose_name='入数')),
                ('Case_su', models.IntegerField(blank=True, null=True, verbose_name='C/S')),
                ('Sum_su', models.IntegerField(verbose_name='合計数量')),
                ('Kingaku', models.IntegerField(blank=True, null=True, verbose_name='金額')),
                ('Siresaki_cd', models.IntegerField(verbose_name='仕入先CD')),
                ('Siresaki_nm', models.CharField(max_length=80, verbose_name='仕入先名')),
                ('Hachu_day', models.CharField(max_length=10, null=True, verbose_name='発注日')),
                ('Yotei_day', models.CharField(blank=True, max_length=100, null=True, verbose_name='予定日')),
                ('Nohin_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='納品日')),
                ('Nohin_tanto_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='納品担当者')),
                ('Tokuisaki_shuka_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='得意先出荷日')),
                ('Syoumikgn', models.CharField(blank=True, max_length=10, null=True, verbose_name='賞味期限')),
                ('Biko', models.CharField(blank=True, max_length=10000, null=True, verbose_name='備考')),
                ('In_tanto_cd', models.IntegerField(null=True, verbose_name='登録担当者コード')),
                ('In_tanto_nm', models.CharField(max_length=80, null=True, verbose_name='登録担当者名')),
                ('In_bumon_cd', models.IntegerField(null=True, verbose_name='登録部門コード')),
                ('In_bumon_nm', models.CharField(max_length=80, null=True, verbose_name='登録部門名')),
                ('In_tanmatu_nm', models.CharField(max_length=100, null=True, verbose_name='登録端末名')),
                ('In_tanmatu_tanto_nm', models.CharField(max_length=80, null=True, verbose_name='登録端末担当者名')),
                ('In_tanmatu_tanto_ip', models.CharField(max_length=1024, null=True, verbose_name='登録端末IP')),
                ('Up_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新年月日')),
                ('Up_tanto_cd', models.IntegerField(null=True, verbose_name='更新担当者コード')),
                ('Up_tanto_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='更新担当者名')),
                ('Up_bumon_cd', models.IntegerField(blank=True, null=True, verbose_name='更新部門コード')),
                ('Up_bumon_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='更新部門名')),
                ('Up_tanmatu_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新端末名')),
                ('Up_tanmatu_tanto_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='更新端末担当者名')),
                ('Up_tanmatu_tanto_ip', models.CharField(blank=True, max_length=1024, null=True, verbose_name='登録端末IP')),
                ('Del_time', models.DateTimeField(blank=True, null=True, verbose_name='削除年月日')),
                ('Del_tanto_cd', models.IntegerField(blank=True, null=True, verbose_name='削除担当者コード')),
                ('Del_tanto_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='削除担当者名')),
                ('Del_bumon_cd', models.IntegerField(blank=True, null=True, verbose_name='削除部門コード')),
                ('Del_bumon_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='削除部門名')),
                ('Del_tanmatu_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='削除端末名')),
                ('Del_tanmatu_tanto_nm', models.CharField(blank=True, max_length=80, null=True, verbose_name='削除端末担当者名')),
                ('Del_tanmatu_tanto_ip', models.CharField(blank=True, max_length=1024, null=True, verbose_name='削除端末IP')),
                ('Del_flg', models.IntegerField(blank=True, default='0', verbose_name='削除フラグ')),
                ('Open_flg', models.IntegerField(blank=True, default='0', verbose_name='公開フラグ')),
                ('Biken_flg', models.IntegerField(blank=True, default='0', verbose_name='美健フラグ')),
                ('Cancel_flg', models.IntegerField(blank=True, default='0', verbose_name='キャンセルフラグ')),
                ('Shouhin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yui.Shouhin')),
            ],
            options={
                'verbose_name': '発注管理T',
                'verbose_name_plural': '発注管理Class',
            },
        ),
    ]
