# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-17 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_oml2',
            name='Shouhin',
        ),
        migrations.AddField(
            model_name='t_oml2',
            name='Shouhin_cd',
            field=models.IntegerField(default=0, verbose_name='商品CD'),
            preserve_default=False,
        ),
    ]
