# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-16 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oml2',
            name='Biken_flg',
            field=models.IntegerField(blank=True, default='0', verbose_name='美健フラグ'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Cancel_flg',
            field=models.IntegerField(blank=True, default='0', verbose_name='キャンセルフラグ'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Del_flg',
            field=models.IntegerField(blank=True, default='0', verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Open_flg',
            field=models.IntegerField(blank=True, default='0', verbose_name='公開フラグ'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Up_bumon_cd',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新部門コード'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Up_bumon_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='更新部門名'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Up_tanmatu_nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='更新端末名'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Up_tanmatu_tanto_ip',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='登録端末IP'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Up_tanmatu_tanto_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='更新端末担当者名'),
        ),
        migrations.AlterField(
            model_name='t_oml2',
            name='Up_tanto_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='更新担当者名'),
        ),
    ]
