# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_oml2',
            name='Shouhin_nm1',
        ),
    ]
