# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_flg',
            field=models.IntegerField(default='0', verbose_name='削除フラグ'),
        ),
    ]
