# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-10 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0002_auto_20200310_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouhin',
            name='Irisu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='Kikaku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='規格'),
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='Siresaki_cd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='Siresaki_nm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Biko',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Bunrui',
            field=models.CharField(max_length=80, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Busyo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Case_su',
            field=models.IntegerField(blank=True, null=True, verbose_name='C/S'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Hachu_nm',
            field=models.CharField(max_length=80, verbose_name='発注者'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Houhou',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='方法'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Irai_day',
            field=models.CharField(max_length=10, verbose_name='依頼日'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Iri_su',
            field=models.IntegerField(blank=True, null=True, verbose_name='入数'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Kingaku',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Nohin_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='納品日'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Nohin_tanto_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='納品担当者'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Siresaki_cd',
            field=models.IntegerField(verbose_name='仕入先CD'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Siresaki_nm',
            field=models.CharField(max_length=80, verbose_name='仕入先名'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Sum_su',
            field=models.IntegerField(verbose_name='合計数量'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Syoumikgn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='賞味期限'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Syuka_kokyaku',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='出荷顧客'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Tokuisaki_shuka_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='得意先出荷日'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Yotei_day',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='予定日'),
        ),
    ]
