# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-10 05:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0005_auto_20200310_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_bumon_cd',
            field=models.IntegerField(blank=True, null=True, verbose_name='削除部門コード'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_bumon_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='削除部門名'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_tanmatu_nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='削除端末名'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_tanmatu_tanto_ip',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='削除端末IP'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_tanmatu_tanto_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='削除端末担当者名'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_tanto_cd',
            field=models.IntegerField(blank=True, null=True, verbose_name='削除担当者コード'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_tanto_nm',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='削除担当者名'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Del_time',
            field=models.DateTimeField(blank=True, verbose_name='削除年月日'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Up_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 5, 33, 8, 933424, tzinfo=utc), null=True, verbose_name='更新年月日'),
        ),
    ]
