# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 07:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0008_auto_20200310_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oml3',
            name='Irai_day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='依頼日'),
        ),
        migrations.AlterField(
            model_name='t_oml3',
            name='Up_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 7, 49, 9, 999561, tzinfo=utc), null=True, verbose_name='更新年月日'),
        ),
    ]
