# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yui', '0009_auto_20200311_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_oml3',
            name='Up_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 14, 31, 55, 843368, tzinfo=utc), null=True, verbose_name='更新年月日'),
        ),
    ]
